### ISSUE TITLE
If Exitcode from wrapped Script is not 0 the output will be discarded.

### ISSUE THREAD

**Issue by dplusf** [jaxxstorm/sensu-wrapper#29]
Hi @jaxxstorm ,

sensu-wrapper will not include output from stdout when Exitcode from wrapped Script is not 0.
working Example:
```
/opt/sensu/embedded/bin/sensu-wrapper/sensu-wrapper -d -n 'foobar' check-http.rb -b --response-code 302 -u http://www.google.de
{"name":"foobar","command":"/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-http.rb -b --response-code 302 -u http://www.google.de","status":0,"output":"CheckHttp OK: 200, 10486 bytes\n\u003c\n"}
```

failed Example:
```
/opt/sensu/embedded/bin/sensu-wrapper/sensu-wrapper -d -n 'foobar' /opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-http.rb -b --response-code 302 -u http://www.google.com
{"name":"foobar","command":"/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-http.rb -b --response-code 302 -u http://www.google.com","**status":1,"output":""**}
```

Is there a way to include the output in case of an failure?

Best
deeks

**Comment by jaxxstorm** [comment]
I'll give it a look as soon as I can, I didn't see this during testing! thanks for the bug

**Comment by jaxxstorm** [comment]
@dplusf what exit code are you expecting here?

**Comment by dplusf** [comment]
@jaxxstorm exit code could be 1 or 2 as in the example. output is empty but should contain the check result

```
{"name":"foobar","command":"/opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-http.rb -b --response-code 302 -u http://www.google.com","**status":1,"output":""**}
```

**Comment by jaxxstorm** [comment]
@dplusf I finally got chance to look into this properly. The issue is [here](https://github.com/jaxxstorm/sensu-wrapper/blob/master/command/command.go#L46) where I make the assumption that anything that fails will send its output to stderr, and in this case the ruby check actually sends all output to stdout. I'll have to rework the logic a bit, I'll try get to that over the weekend. Thanks for the report!
